-- Drop all foreign key constraints to allow data import without validation
-- This allows importing data even when referenced records don't exist yet

-- Interim table constraints
ALTER TABLE aca_employee_monthly_enrollment DROP CONSTRAINT IF EXISTS aca_employee_monthly_enrollment_company_code_employee_id_fkey;
ALTER TABLE aca_employee_monthly_offer DROP CONSTRAINT IF EXISTS aca_employee_monthly_offer_company_code_employee_id_fkey;
ALTER TABLE aca_employee_monthly_status DROP CONSTRAINT IF EXISTS aca_employee_monthly_status_company_code_employee_id_fkey;

-- Source table constraints
ALTER TABLE employee_address DROP CONSTRAINT IF EXISTS employee_address_company_code_employee_id_fkey;
ALTER TABLE employee_census DROP CONSTRAINT IF EXISTS employee_census_company_code_fkey;
ALTER TABLE employee_dependent DROP CONSTRAINT IF EXISTS employee_dependent_company_code_employee_id_fkey;
ALTER TABLE employee_plan_eligibility DROP CONSTRAINT IF EXISTS employee_plan_eligibility_company_code_employee_id_fkey;
ALTER TABLE employee_plan_eligibility DROP CONSTRAINT IF EXISTS employee_plan_eligibility_company_code_plan_code_fkey;
ALTER TABLE employee_plan_enrollment DROP CONSTRAINT IF EXISTS employee_plan_enrollment_company_code_employee_id_fkey;
ALTER TABLE employee_plan_enrollment DROP CONSTRAINT IF EXISTS employee_plan_enrollment_company_code_plan_code_fkey;
ALTER TABLE employee_waiting_period DROP CONSTRAINT IF EXISTS employee_waiting_period_company_code_employee_id_fkey;
ALTER TABLE payroll_hours DROP CONSTRAINT IF EXISTS payroll_hours_company_code_employee_id_fkey;
ALTER TABLE plan_enrollment_cost DROP CONSTRAINT IF EXISTS plan_enrollment_cost_enrollment_id_fkey;
ALTER TABLE plan_master DROP CONSTRAINT IF EXISTS plan_master_company_code_fkey;
